### ISSUE TITLE
GPG Key

### ISSUE THREAD

**Issue by peterdavidfagan** [moveit/moveit2_packages#1]
Is there a GPG key or deploy key for this repository? 

Apologies if this is a naive question. Installing debians locally works great, wished to ensure apt is set up to automatically update the packages. 

I have already executed:

```
echo "deb [trusted=yes] https://raw.githubusercontent.com/moveit/moveit2_packages/jammy-rolling/ ./" | sudo tee /etc/apt/sources.list.d/moveit_moveit2_packages.list
echo "yaml https://raw.githubusercontent.com/moveit/moveit2_packages/jammy-rolling/local.yaml rolling" | sudo tee /etc/ros/rosdep/sources.list.d/1-moveit_moveit2_packages.list
```

**Comment by jspricke** [comment]
There is non, see my blog post on some security considerations: https://picknik.ai/ros/debian/packaging/2023/02/27/packaging-ros-with-github-actions.html

**Comment by peterdavidfagan** [comment]
Thanks for the super quick response @jspricke, I'll look at the linked blog post.

**Comment by peterdavidfagan** [comment]
Hi @jspricke, 

I am looking to use apt to download the package files for building Python API documentation as discussed in https://github.com/ros-planning/moveit2_tutorials/pull/504. 

Currently apt ignores `moveit_moveit2_packages.list` when performing `sudo apt update`.

```
Ign:2 https://raw.githubusercontent.com/moveit/moveit2_packages/jammy-rolling ./ InRelease
Ign:10 https://raw.githubusercontent.com/moveit/moveit2_packages/jammy-rolling ./ Release.gpg
```

Note: I have added the repository to my sources.list.d as per the README.md for the jammy-rolling branch. I believe this relates to authentication, is there a recommended approach that others are taking to bypass this issue? It seems like `trusted=true` is not working on my system.

**Comment by peterdavidfagan** [comment]
<img width="623" alt="Screenshot 2023-03-16 at 14 26 21" src="https://user-images.githubusercontent.com/42982057/225631252-0cd2761e-6abb-4f0c-8179-75ec3df52851.png">

**Comment by jspricke** [comment]
Can you please post the complete output of `sudo apt update`? Those two `Ign` lines are fine. Also `apt policy ros-rolling-moveit-common´.
For the website screenshot, the URL for the browser is: https://github.com/moveit/moveit2_packages/tree/jammy-rolling.

**Comment by peterdavidfagan** [comment]
Hi @jspricke, 

My apologies, I was making a silly blunder it works as expected now.
