### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by riv-tnoble** [moveit/moveit2_packages#7]
Hi,

After making some changes on moveit, I was directed to this repository by @sjahr via [this documentation page](https://moveit.ai/moveit%202/ros/2023/05/31/balancing-stability-and-development.html) as a way of testing the changes on humble without having to build from source.

I've followed the instructions, however, the changes I've made aren't showing up. I've also noticed that the last changes to this repo & action run are from a year ago. My changes were merged into moveit2 main yesterday so I could just be being too hasty, but I wanted to check if this repository and the method described in the above docs are still relevant?

**Comment by rr-tom-noble** [comment]
Checking the package versions is also consistent with the idea that they haven't been updated in a year:

```
Package: ros-humble-moveit
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 49
Maintainer: Henning Kayser <henningkayser@picknik.ai>
Architecture: amd64
Version: 2.5.5-1jammy.20241028.145304
Depends: ros-humble-moveit-core, ros-humble-moveit-planners, ros-humble-moveit-plugins, ros-humble-moveit-ros, ros-humble-moveit-setup-assistant, ros-humble-ros-workspace
Description: Meta package that contains all essential packages of MoveIt 2
Homepage: http://moveit.ros.org
```

**Comment by jspricke** [comment]
This is no longer updated, see also #6.

**Comment by riv-tnoble** [comment]
The docs suggest that the packages are updated nightly, but it looks like the most recent versions are from Oct 28th?

```
Package: ros-humble-pilz-industrial-motion-planner
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 8381
Maintainer: Christian Henkel <c.henkel@pilz.de>
Architecture: amd64
Version: 2.5.5-1jammy.20241028.140629
Depends: libc6 (>= 2.34), libconsole-bridge1.0 (>= 1.0.1+dfsg2), libgcc-s1 (>= 3.3.1), liborocos-kdl1.5 (>= 1.5.1), libstdc++6 (>= 11), libtinyxml2-9 (>= 8.0.0), ros-humble-moveit-core, ros-humble-moveit-ros-move-group, ros-humble-moveit-ros-planning, ros-humble-eigen3-cmake-module, ros-humble-geometry-msgs, ros-humble-moveit-common, ros-humble-moveit-msgs, ros-humble-moveit-ros-planning-interface, ros-humble-orocos-kdl-vendor, ros-humble-pluginlib, ros-humble-rclcpp, ros-humble-tf2, ros-humble-tf2-eigen, ros-humble-tf2-eigen-kdl, ros-humble-tf2-geometry-msgs, ros-humble-tf2-kdl, ros-humble-tf2-ros, ros-humble-ros-workspace
Description: MoveIt plugin to generate industrial trajectories PTP, LIN, CIRC and sequences thereof.
Homepage: http://moveit.ros.org
```

**Comment by riv-tnoble** [comment]
Thanks for the quick response and understood. Closing this isssue as answered
